param(
    [Parameter(Position=0)]
    [ValidateSet("status","publish")]
    [string]$Action = "status",

    [string]$ConfigPath = (Join-Path $PSScriptRoot "sync.leanpub.config.json"),
    [string]$SourceManuscriptPath,
    [string]$PublishingRepoPath,
    [string]$PublishingManuscriptPath,
    [string]$SpineFile,
    [string]$StateFile
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-FullPathValue { param([string]$PathValue) return [System.IO.Path]::GetFullPath($PathValue) }
function Join-FullPath { param([string]$Base,[string]$Child) if ([System.IO.Path]::IsPathRooted($Child)) { return Get-FullPathValue $Child }; return Get-FullPathValue (Join-Path $Base $Child) }
function Convert-ToManifestPath { param([string]$PathValue) return ($PathValue -replace '\\','/').TrimStart('/') }
function Test-PathInside { param([string]$Child,[string]$Root) $c=(Get-FullPathValue $Child).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar); $r=(Get-FullPathValue $Root).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar); return ($c.Equals($r,[StringComparison]::OrdinalIgnoreCase) -or $c.StartsWith($r + [IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase) -or $c.StartsWith($r + [IO.Path]::AltDirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)) }
function Assert-ChildPath { param([string]$Child,[string]$Root,[string]$Label) if (-not (Test-PathInside $Child $Root)) { throw "$Label resolves outside approved root: $Child" } }
function Test-UnsafeRelativePath { param([string]$Value) if ([string]::IsNullOrWhiteSpace($Value)) { return $true }; if ([System.IO.Path]::IsPathRooted($Value)) { return $true }; if ($Value -match '^[A-Za-z]:') { return $true }; if ($Value.StartsWith('\\')) { return $true }; $parts = ($Value -replace '\\','/').Split('/'); return @($parts | Where-Object { $_ -eq '..' }).Count -gt 0 }
function Get-DefaultStateFile { param([string]$ConfigPathValue) $dir=Split-Path -Parent $ConfigPathValue; $leaf=Split-Path -Leaf $ConfigPathValue; return Join-Path $dir ([IO.Path]::GetFileNameWithoutExtension($leaf) + ".state.json") }
function Get-JsonProperty { param($Object,[string]$Name) if ($null -ne $Object -and $null -ne $Object.PSObject.Properties[$Name]) { return [string]$Object.$Name }; return $null }

function Get-LeanpubConfig {
    param([string]$ConfigPathValue,[string]$CliSource,[string]$CliRepo,[string]$CliManuscript,[string]$CliSpine,[string]$CliState)
    $resolvedConfig = Get-FullPathValue $ConfigPathValue
    $configDir = Split-Path -Parent $resolvedConfig
    if (-not (Test-Path -LiteralPath $resolvedConfig -PathType Leaf)) { throw "Config file not found: $resolvedConfig" }
    try { $raw = Get-Content -LiteralPath $resolvedConfig -Raw | ConvertFrom-Json } catch { throw "Malformed JSON config '$resolvedConfig': $($_.Exception.Message)" }
    $source = if ($CliSource) { $CliSource } else { Get-JsonProperty $raw 'source_manuscript_path' }
    $repo = if ($CliRepo) { $CliRepo } else { Get-JsonProperty $raw 'publishing_repo_path' }
    $pubMan = if ($CliManuscript) { $CliManuscript } else { Get-JsonProperty $raw 'publishing_manuscript_path' }
    $spine = if ($CliSpine) { $CliSpine } else { Get-JsonProperty $raw 'spine_file' }
    $state = if ($CliState) { $CliState } else { Get-JsonProperty $raw 'state_file' }
    foreach ($pair in @(@('source_manuscript_path',$source),@('publishing_repo_path',$repo),@('publishing_manuscript_path',$pubMan),@('spine_file',$spine))) { if ([string]::IsNullOrWhiteSpace($pair[1])) { throw "Missing required config value: $($pair[0])" } }
    if (Test-UnsafeRelativePath $pubMan) { throw "publishing_manuscript_path must be a safe relative path: $pubMan" }
    if (Test-UnsafeRelativePath $spine) { throw "spine_file must be a safe relative path: $spine" }
    $sourceFull=Get-FullPathValue $source; $repoFull=Get-FullPathValue $repo; $pubFull=Join-FullPath $repoFull $pubMan; $spineFull=Join-FullPath $sourceFull $spine
    $stateFull = if ($state) { Join-FullPath $configDir $state } else { Get-DefaultStateFile $resolvedConfig }
    [PSCustomObject]@{ config_path=$resolvedConfig; source_manuscript_path=$sourceFull; publishing_repo_path=$repoFull; publishing_manuscript_path=$pubFull; publishing_manuscript_relative=Convert-ToManifestPath $pubMan; spine_file=$spine; spine_path=$spineFull; state_file=$stateFull }
}

function Confirm-NoSymlinkInPath { param([string]$FullPath,[string]$RootPath,[string]$Label) Assert-ChildPath $FullPath $RootPath $Label; $root=(Get-FullPathValue $RootPath).TrimEnd('\','/'); $cur=$root; $rel=(Get-FullPathValue $FullPath).Substring($root.Length).TrimStart('\','/'); foreach($part in (($rel -replace '\\','/').Split('/') | Where-Object { $_ })) { $cur=Join-Path $cur $part; if (Test-Path -LiteralPath $cur) { $item=Get-Item -LiteralPath $cur -Force; if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw "$Label passes through a reparse point or symbolic link: $cur" } } } }
function Confirm-Safety { param($Config,[switch]$RequireTargetGit) Confirm-DirectoryExists $Config.source_manuscript_path; Confirm-DirectoryExists $Config.publishing_repo_path; if (-not (Test-PathInside $Config.publishing_manuscript_path $Config.publishing_repo_path)) { throw "Publishing manuscript path is outside publishing repo: $($Config.publishing_manuscript_path)" }; if ((Get-FullPathValue $Config.publishing_manuscript_path).TrimEnd('\','/').Equals((Get-FullPathValue $Config.publishing_repo_path).TrimEnd('\','/'),[StringComparison]::OrdinalIgnoreCase)) { throw "Publishing manuscript path must not be the repository root." }; if ((Test-PathInside $Config.publishing_manuscript_path $Config.source_manuscript_path) -or (Test-PathInside $Config.source_manuscript_path $Config.publishing_manuscript_path)) { throw "Dangerous source/target overlap rejected: '$($Config.source_manuscript_path)' and '$($Config.publishing_manuscript_path)'" }; if ($RequireTargetGit -and -not (Test-Path -LiteralPath (Join-Path $Config.publishing_repo_path '.git'))) { throw "Publishing repository is not a Git working tree (missing .git): $($Config.publishing_repo_path)" } }
function Confirm-DirectoryExists { param([string]$PathValue) if (-not (Test-Path -LiteralPath $PathValue -PathType Container)) { throw "Directory not found: $PathValue" } }

function Get-HashEntry { param([string]$Path,[string]$Relative) $h=[Security.Cryptography.SHA256]::Create(); try { $s=[IO.File]::OpenRead($Path); try { $bytes=$h.ComputeHash($s) } finally { $s.Dispose() } } finally { $h.Dispose() }; [PSCustomObject]@{ path=(Convert-ToManifestPath $Relative); length=(Get-Item -LiteralPath $Path).Length; sha256=([BitConverter]::ToString($bytes).Replace('-','').ToLowerInvariant()) } }
function Get-ActiveSpineEntries { param($Config) if (-not (Test-Path -LiteralPath $Config.spine_path -PathType Leaf)) { throw "Spine file not found: $($Config.spine_path)" }; Confirm-NoSymlinkInPath $Config.spine_path $Config.source_manuscript_path 'Spine file'; $seen=@{}; $entries=New-Object System.Collections.Generic.List[string]; foreach($line in Get-Content -LiteralPath $Config.spine_path) { $t=$line.Trim(); if (-not $t -or $t.StartsWith('#')) { continue }; if (Test-UnsafeRelativePath $t) { throw "Unsafe spine entry: $t" }; $rel=Convert-ToManifestPath $t; if ($seen.ContainsKey($rel.ToLowerInvariant())) { throw "Duplicate spine entry: $rel" }; $full=Join-FullPath $Config.source_manuscript_path $rel; Assert-ChildPath $full $Config.source_manuscript_path 'Spine entry'; if (-not (Test-Path -LiteralPath $full -PathType Leaf)) { if (Test-Path -LiteralPath $full -PathType Container) { throw "Spine entry is a directory where a file is required: $rel" }; throw "Active manuscript file not found: $rel" }; Confirm-NoSymlinkInPath $full $Config.source_manuscript_path 'Spine entry'; $seen[$rel.ToLowerInvariant()]=$true; $entries.Add($rel) }
    if ($entries.Count -eq 0) { throw "Spine contains no active manuscript files: $($Config.spine_path)" }; return @($entries) }
function Get-ImageTargets { param([string]$Text) $matches=[regex]::Matches($Text,'!\[[^\]]*\]\((?<target><[^>]+>|[^)\s]+)(?:\s+"[^"]*")?\)'); foreach($m in $matches){ $v=$m.Groups['target'].Value.Trim(); if ($v.StartsWith('<') -and $v.EndsWith('>')) { $v=$v.Substring(1,$v.Length-2) }; $v } }
function Resolve-ResourceReference { param([string]$Reference,[string]$ManuscriptRelative,$Config) $r=$Reference.Trim(); if (-not $r -or $r.StartsWith('#') -or $r -match '^(?i)(https?://|data:|mailto:)') { return $null }; $r=($r -split '[?#]',2)[0]; try { $r=[Uri]::UnescapeDataString($r) } catch {}; if (Test-UnsafeRelativePath $r) { throw "Unsafe resource reference '$Reference' in '$ManuscriptRelative'" }; $baseDir=Split-Path -Parent $ManuscriptRelative; $combined=if ($baseDir) { Join-Path $baseDir $r } else { $r }; $rel=Convert-ToManifestPath $combined; if (-not ($rel.StartsWith('resources/',[StringComparison]::OrdinalIgnoreCase))) { throw "Referenced local resource must be under resources/: '$Reference' in '$ManuscriptRelative'" }; $full=Join-FullPath $Config.source_manuscript_path $rel; Assert-ChildPath $full $Config.source_manuscript_path 'Resource'; if (-not (Test-Path -LiteralPath $full -PathType Leaf)) { if (Test-Path -LiteralPath $full -PathType Container) { throw "Referenced resource is a directory: $rel" }; throw "Referenced resource not found: $rel" }; Confirm-NoSymlinkInPath $full $Config.source_manuscript_path 'Resource'; return $rel }
function Get-ReferencedResources { param([string[]]$ActiveFiles,$Config) $set=@{}; foreach($rel in $ActiveFiles){ $full=Join-FullPath $Config.source_manuscript_path $rel; $text=Get-Content -LiteralPath $full -Raw; foreach($target in Get-ImageTargets $text){ $res=Resolve-ResourceReference $target $rel $Config; if ($res) { $set[$res.ToLowerInvariant()]=$res } } }; return @($set.Values | Sort-Object) }
function Build-SourceManifest { param($Config,[ref]$ActiveCount,[ref]$ResourceCount) $active=Get-ActiveSpineEntries $Config; $resources=Get-ReferencedResources $active $Config; $ActiveCount.Value=$active.Count; $ResourceCount.Value=$resources.Count; $paths=@((Convert-ToManifestPath $Config.spine_file)) + $active + $resources; $unique=@{}; foreach($p in $paths){$unique[$p.ToLowerInvariant()]=$p}; return @($unique.Values | Sort-Object | ForEach-Object { Get-HashEntry (Join-FullPath $Config.source_manuscript_path $_) $_ }) }
function Build-TargetManifest { param($Config) if (-not (Test-Path -LiteralPath $Config.publishing_manuscript_path -PathType Container)) { return @() }; Get-ChildItem -LiteralPath $Config.publishing_manuscript_path -Recurse -File -Force | Sort-Object FullName | ForEach-Object { $rel=$_.FullName.Substring((Get-FullPathValue $Config.publishing_manuscript_path).TrimEnd('\','/').Length).TrimStart('\','/'); Get-HashEntry $_.FullName $rel } }
function Compare-Manifests { param([array]$Source,[array]$Target) $s=@{};$t=@{}; foreach($e in $Source){$s[$e.path.ToLowerInvariant()]=$e}; foreach($e in $Target){$t[$e.path.ToLowerInvariant()]=$e}; $all=@($s.Keys+$t.Keys|Sort-Object -Unique); foreach($k in $all){ if(-not $t.ContainsKey($k)){[PSCustomObject]@{operation='ADD';path=$s[$k].path;source=$s[$k]}} elseif(-not $s.ContainsKey($k)){[PSCustomObject]@{operation='DELETE';path=$t[$k].path;target=$t[$k]}} elseif($s[$k].sha256 -ne $t[$k].sha256){[PSCustomObject]@{operation='UPDATE';path=$s[$k].path;source=$s[$k];target=$t[$k]}} else {[PSCustomObject]@{operation='UNCHANGED';path=$s[$k].path;source=$s[$k];target=$t[$k]}} } }
function Write-Summary { param($Config,[int]$Active,[int]$Resources,[array]$Diffs) Write-Host "Source manuscript path: $($Config.source_manuscript_path)"; Write-Host "Publishing repository path: $($Config.publishing_repo_path)"; Write-Host "Publishing manuscript path: $($Config.publishing_manuscript_path)"; Write-Host "Spine path: $($Config.spine_path)"; Write-Host "Active manuscript files: $Active"; Write-Host "Referenced resources: $Resources"; foreach($op in 'ADD','UPDATE','DELETE','UNCHANGED'){ Write-Host "$op count: " (@($Diffs|Where-Object operation -eq $op).Count) }; foreach($op in 'ADD','UPDATE','DELETE'){ $items=@($Diffs|Where-Object operation -eq $op|Sort-Object path); if($items.Count){ Write-Host "$op paths:"; $items|ForEach-Object{Write-Host "  $($_.path)"} } }; if(@($Diffs|Where-Object { $_.operation -ne 'UNCHANGED'}).Count -eq 0){ Write-Host "Publication projection is synchronized." } else { Write-Host "Publication projection has pending changes." } }
function Invoke-LeanpubStatus { param($Config) Confirm-Safety $Config; $a=0;$r=0; $source=Build-SourceManifest $Config ([ref]$a) ([ref]$r); $target=Build-TargetManifest $Config; $diffs=@(Compare-Manifests $source $target); Write-Summary $Config $a $r $diffs; return [PSCustomObject]@{source=$source;diffs=$diffs;active=$a;resources=$r} }
function Copy-ManifestFile { param($Config,$Entry) $src=Join-FullPath $Config.source_manuscript_path $Entry.path; $dst=Join-FullPath $Config.publishing_manuscript_path $Entry.path; $dir=Split-Path -Parent $dst; if(-not(Test-Path -LiteralPath $dir -PathType Container)){New-Item -ItemType Directory -Path $dir -Force|Out-Null}; Copy-Item -LiteralPath $src -Destination $dst -Force }
function Remove-EmptyDirs { param([string]$Root) if(-not(Test-Path -LiteralPath $Root -PathType Container)){return}; Get-ChildItem -LiteralPath $Root -Directory -Recurse -Force | Sort-Object FullName -Descending | ForEach-Object { if(-not @(Get-ChildItem -LiteralPath $_.FullName -Force).Count){ Remove-Item -LiteralPath $_.FullName -Force } } }
function Save-LeanpubState { param($Config,[array]$Manifest) $dir=Split-Path -Parent $Config.state_file; if(-not(Test-Path -LiteralPath $dir -PathType Container)){New-Item -ItemType Directory -Path $dir -Force|Out-Null}; $state=[PSCustomObject]@{schema_version=1;last_publish_utc=(Get-Date).ToUniversalTime().ToString('o');source_manuscript_path=$Config.source_manuscript_path;publishing_repo_path=$Config.publishing_repo_path;publishing_manuscript_path=$Config.publishing_manuscript_path;spine_file=$Config.spine_file;manifest=$Manifest}; $json=$state|ConvertTo-Json -Depth 8; [IO.File]::WriteAllText($Config.state_file,$json,(New-Object Text.UTF8Encoding($false))) }
function Invoke-LeanpubPublish { param($Config) Confirm-Safety $Config -RequireTargetGit; $a=0;$r=0; $source=Build-SourceManifest $Config ([ref]$a) ([ref]$r); if(-not(Test-Path -LiteralPath $Config.publishing_manuscript_path -PathType Container)){New-Item -ItemType Directory -Path $Config.publishing_manuscript_path -Force|Out-Null}; $target=Build-TargetManifest $Config; $diffs=@(Compare-Manifests $source $target); Write-Summary $Config $a $r $diffs; foreach($d in @($diffs|Where-Object operation -in @('ADD','UPDATE')|Sort-Object path)){ Write-Host "$($d.operation) $($d.path)"; Copy-ManifestFile $Config $d.source }; foreach($d in @($diffs|Where-Object operation -eq 'DELETE'|Sort-Object path)){ $dst=Join-FullPath $Config.publishing_manuscript_path $d.path; Assert-ChildPath $dst $Config.publishing_manuscript_path 'Delete target'; Write-Host "DELETE $($d.path)"; Remove-Item -LiteralPath $dst -Force }; Remove-EmptyDirs $Config.publishing_manuscript_path; Save-LeanpubState $Config $source }

$config=Get-LeanpubConfig $ConfigPath $SourceManuscriptPath $PublishingRepoPath $PublishingManuscriptPath $SpineFile $StateFile
if ($Action -eq 'status') { Invoke-LeanpubStatus $config | Out-Null } else { Invoke-LeanpubPublish $config }
